---
#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        run: |
          zip -r CheDocs.zip CheDocs
          gh release create v$GITHUB_RUN_NUMBER 'CheDocs.zip'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
